htmlTags = {
  "anchor": "a",
	"abbreviation": "abbr",
	"address": "address",
	"area": "area",
	"article": "article",
	"aside": "aside",
	"audio": "audio",
	"bold": "b",
	"base": "base",
	"BDI": "bdi",
	"BDO": "bdo",
	"block quote": "blockquote",
	"break":"br",
	"body": "body",
	"button": "button",
	"Canvas": "canvas",
	"[table] caption": "caption",
	"cite": "cite",
	"code": "code",
	"color": "color",
	"table column": "col",
	"table column group": "colgroup",
	"command": "command",
	"data list": "datalist",
	"definition description": "dd",
	"del": "del",
	"details": "details",
	"dfn": "dfn",
	"div": "div",
	"dl": "dl",
	"dt": "dt",
	"em": "em",
	"embed": "embed",
	"field set": "fieldset",
	"figure caption": "figcaption",
	"figure": "figure",
	"footer": "footer",
	"form": "form",
	"H1": "h1",
	"H2": "h2",
	"H3": "h3",
	"H4": "h4",
	"H5": "h5",
	"H6": "h6",
	"head": "head",
	"H group": "hgroup",
	"HR": "hr",
	"HTML": "html",
	"HTML": "HTML",
	"I": "i",
	"I frame": "iframe",
	"image": "img",
	"input": "input",
	"INS": "ins",
	"key gen": "keygen",
	"KBD": "kbd",
	"label": "label",
	"legend": "legend",
	"list item": "li",
	"Link": "link",
	"Mark": "mark",
	"menu": "menu",
	"meta": "meta",
	"meter": "meter",
	"navigation": "nav",
	"no script": "noscript",
	"object": "object",
	"ordered list": "ol",
	"option group": "optgroup",
	"option": "option",
	"output": "output",
	"paragraph": "p",
	"parameter": "param",
	"pre": "pre",
	"progress": "progress",
	"g": "g",
	"RP": "rp",
	"RT": "rt",
	"Ruby": "ruby",
	"s": "s",
	"sample": "samp",
	"script": "script",
	"section": "section",
	"select": "select",
	"small": "small",
	"source": "source",
	"span": "span",
	"strong": "strong",
	"style": "style",
	"sub": "sub",
	"summary": "summary",
	"superscript": "sup",
	"table": "table",
	"T body": "tbody",
	# means the same thing and represents a table cell
	"TD": "td",     "table cell": "td",
	"textarea": "textarea",
	"T foot": "tfoot",
	# means the same thing and represents a table header
	"TH": "th", "table header": "th",
	"T head": "thead",
	"time": "time",
	"title": "title",
	# means the same thing and represents a table row
	"table row": "tr",   "TR": "tr",
	"track": "track",
	"unordered list": "ul",
	"variable": "var",
	"video": "video",
	"label": "label",
	}
tagsAlpha = {
	"one": "0.1",
	"two": "0.2",
	"three": "0.3",
	"four": "0.4",
	"five": "0.5",
	"six": "0.6",
	"seven": "0.7",
	"eight": "0.8",
	"nine": "0.9",
	"ten": "1.0",
	}
tagsCss = {
	"background":"background",
	"border":"border",
	"border bottom":"border-bottom",
	"border top":"border-top",
	"border left":"border-left",
	"border right":"border-right",
	"box":"box",
	"margin":"margin",
	"padding":"padding",
	"font":"font",
	"clear":"clear",
	"display":"display",
	"float":"float",
	"marquee":"marquee",
	"overflow":"overflow",
	"rotation":"rotation",
	"visibility":"visibility",
	"direction":"direction",
	"letter":"letter",
	"hanging punctuation":"hanging-punctuation",
	"punctuation trim":"punctuation-trim",
	"text":"text",
	"word":"word",
	"list":"list",
	"marker":"marker",
	"column":"column",
	"grid":"grid",
	"hyphenate":"hyphenate",
	"line":"line",
	"vertical":"vertical",
	"target":"target",
	"bottom":"bottom",
	"clip":"clip",
	"left":"left",
	"position":"position",
	"right":"right",
	"top":"top",
	"Z index":"z-index",
	}
tagsCssSuffix = {
	"attachment":"-attachment",
	"break":"-break",
	"clip":"-clip",
	"color":"-color",
	"image":"-image",
	"origin":"-origin",
	"position":"-position",
	"repeat":"-repeat",
	"size":"-size",
	"radius":"-radius",
	"shadow":"-shadow",
	"height":"-height",
	"width":"-width",
	"right":"-right",
	"left":"-left",
	"bottom":"-bottom",
	"top":"-top",
	"family":"-family",
	"speed":"-speed",
	"direction":"-direction",
	"play count":"-play-count",
	"loop":"-loop",
	"style":"-style",
	"x":"-x",
	"y":"-y",
	"point":"-point",
	"align":"-align",
	"align last":"-align-last",
	"decoration":"-decoration",
	"emphasis":"-emphasis",
	"indent":"-indent",
	"justify":"-justify",
	"outline":"-outline",
	"transform":"-transform",
	"wrap":"-wrap",
	"spacing":"-spacing",
	"style image":"-style-image",
	"style position":"-style-position",
	"style type":"-style-type",
	"offset":"-offset",
	"count":"-count",
	"fill":"-fill",
	"gap":"-gap",
	"rule color":"-rule-color",
	"rule style":"-rule-style",
	"rule width":"-rule-width",
	"span":"-span",
	"columns":"-columns",
	"rows":"-rows",
	"after":"-after",
	"before":"-before",
	"character":"-character",
	"lines":"-lines",
	"resource":"-resource",
	"resolution":"-resolution",
	"stacking":"-stacking",
	"stacking strategy":"-stacking-strategy",
	"stacking ruby":"-stacking-ruby",
	"stacking shift":"-stacking-shift",
	"name":"-name",
	"new":"-new",

	}
tagsCssPrefix = {
	"min":"min-",
	"max":"max-",
	}
tagsBrowserPrefix = {
	"Mozilla":"-moz-",
	"WebKit":"-webkit-",
	"Opera":"-o-",
	"Internet Explorer":"-ms-",
	}
tagsTarget = {
	"blank": "_blank",
	"parent": "_parent",
	"self": "_self",
	"top": "_top",
	"CSS": "text/css"
	}
tagsColor = {
	"red": "255,0,0",
	"yellow": "255,255,0",
	"blue": "0,0,255",
	"green": "0,255,0",
	"orange": "255,127,0",
	"black": "0,0,0",
	"white": "255,255,255",
	}
tagsAttribute = {
	"ID": "id",
	"width": "width",
	"height": "height",
	"class": "class",
	"color": "color",
	"style": "style",
	"title": "title",
	"source": "src",
	"HREF": "href",
	"relationship": "rel",
	"target": "target",
	"type": "type",
	"background color":"background-color",
	}
tagsCSSlist = {
	"animation" : "animation",
	"appearance" : "appearance",
	"backface-visibility" : "backface-visibility",
	"background" : "background",
	"background" : "background",
	"background-attachment" : "background-attachment",
	"background-color" : "background-color",
	"background-image" : "background-image",
	"background-position" : "background-position",
	"background-repeat" : "background-repeat",
	"background-clip" : "background-clip",
	"background-origin" : "background-origin",
	"background-size" : "background-size",
	"border" : "border",
	"border" : "border",
	"border-bottom" : "border-bottom",
	"border-bottom-color" : "border-bottom-color",
	"border-bottom-style" : "border-bottom-style",
	"border-bottom-width" : "border-bottom-width",
	"border-collapse" : "border-collapse",
	"border-color" : "border-color",
	"border-left" : "border-left",
	"border-left-color" : "border-left-color",
	"border-left-style" : "border-left-style",
	"border-left-width" : "border-left-width",
	"border-right" : "border-right",
	"border-right-color" : "border-right-color",
	"border-right-style" : "border-right-style",
	"border-right-width" : "border-right-width",
	"border-spacing" : "border-spacing",
	"border-style" : "border-style",
	"border-top" : "border-top",
	"border-top-color" : "border-top-color",
	"border-top-style" : "border-top-style",
	"border-top-width" : "border-top-width",
	"border-width" : "border-width",
	"border-bottom-left-radius" : "border-bottom-left-radius",
	"border-bottom-right-radius" : "border-bottom-right-radius",
	"border-image" : "border-image",
	"border-image-outset" : "border-image-outset",
	"border-image-repeat" : "border-image-repeat",
	"border-image-slice" : "border-image-slice",
	"border-image-source" : "border-image-source",
	"border-image-width" : "border-image-width",
	"border-radius" : "border-radius",
	"border-top-left-radius" : "border-top-left-radius",
	"border-top-right-radius" : "border-top-right-radius",
	"bottom" : "bottom",
	"box" : "box",
	"box-align" : "box-align",
	"box-direction" : "box-direction",
	"box-flex" : "box-flex",
	"box-flex-group" : "box-flex-group",
	"box-lines" : "box-lines",
	"box-ordinal-group" : "box-ordinal-group",
	"box-orient" : "box-orient",
	"box-pack" : "box-pack",
	"box-sizing" : "box-sizing",
	"box-shadow" : "box-shadow",
	"caption-side" : "caption-side",
	"clear" : "clear",
	"clip" : "clip",
	"color" : "color",
	"column" : "column",
	"column-count" : "column-count",
	"column-fill" : "column-fill",
	"column-gap" : "column-gap",
	"column-rule" : "column-rule",
	"column-rule-color" : "column-rule-color",
	"column-rule-style" : "column-rule-style",
	"column-rule-width" : "column-rule-width",
	"column-span" : "column-span",
	"column-width" : "column-width",
	"columns" : "columns",
	"content" : "content",
	"counter-increment" : "counter-increment",
	"counter-reset" : "counter-reset",
	"cursor" : "cursor",
	"direction" : "direction",
	"display" : "display",
	"empty-cells" : "empty-cells",
	"float" : "float",
	"font" : "font",
	"font" : "font",
	"font-family" : "font-family",
	"font-size" : "font-size",
	"font-style" : "font-style",
	"font-variant" : "font-variant",
	"font-weight" : "font-weight",
	"font-face" : "@font-face",
	"font-size-adjust" : "font-size-adjust",
	"font-stretch" : "font-stretch",
	"grid-columns" : "grid-columns",
	"grid-rows" : "grid-rows",
	"hanging-punctuation" : "hanging-punctuation",
	"height" : "height",
	"icon" : "icon",
	"keyframes" : "@keyframes",
	"left" : "left",
	"letter-spacing" : "letter-spacing",
	"line-height" : "line-height",
	"list-style" : "list-style",
	"list-style" : "list-style",
	"list-style-image" : "list-style-image",
	"list-style-position" : "list-style-position",
	"list-style-type" : "list-style-type",
	"margin" : "margin",
	"margin" : "margin",
	"margin-bottom" : "margin-bottom",
	"margin-left" : "margin-left",
	"margin-right" : "margin-right",
	"margin-top" : "margin-top",
	"max-height" : "max-height",
	"max-width" : "max-width",
	"min-height" : "min-height",
	"min-width" : "min-width",
	"nav" : "nav",
	"nav-down" : "nav-down",
	"nav-index" : "nav-index",
	"nav-left" : "nav-left",
	"nav-right" : "nav-right",
	"nav-up" : "nav-up",
	"opacity" : "opacity",
	"outline" : "outline",
	"outline" : "outline",
	"outline-color" : "outline-color",
	"outline-offset" : "outline-offset",
	"outline-style" : "outline-style",
	"outline-width" : "outline-width",
	"overflow" : "overflow",
	"overflow-x" : "overflow-x",
	"overflow-y" : "overflow-y",
	"padding" : "padding",
	"padding" : "padding",
	"padding-bottom" : "padding-bottom",
	"padding-left" : "padding-left",
	"padding-right" : "padding-right",
	"padding-top" : "padding-top",
	"page-break" : "page-break",
	"page-break-after" : "page-break-after",
	"page-break-before" : "page-break-before",
	"page-break-inside" : "page-break-inside",
	"perspective" : "perspective",
	"perspective-origin" : "perspective-origin",
	"position" : "position",
	"punctuation-trim" : "punctuation-trim",
	"quotes" : "quotes",
	"resize" : "resize",
	"right" : "right",
	"rotation" : "rotation",
	"rotation-point" : "rotation-point",
	"table-layout" : "table-layout",
	"target" : "target",
	"target" : "target",
	"target-name" : "target-name",
	"target-new" : "target-new",
	"target-position" : "target-position",
	"text" : "text",
	"text-align" : "text-align",
	"text-decoration" : "text-decoration",
	"text-indent" : "text-indent",
	"text-justify" : "text-justify",
	"text-outline" : "text-outline",
	"text-overflow" : "text-overflow",
	"text-shadow" : "text-shadow",
	"text-transform" : "text-transform",
	"text-wrap" : "text-wrap",
	"top" : "top",
	"transform" : "transform",
	"transform" : "transform",
	"transform-origin" : "transform-origin",
	"transform-style" : "transform-style",
	"transition" : "transition",
	"transition" : "transition",
	"transition-property" : "transition-property",
	"transition-duration" : "transition-duration",
	"transition-timing-function" : "transition-timing-function",
	"transition-delay" : "transition-delay",
	"vertical-align" : "vertical-align",
	"visibility" : "visibility",
	"width" : "width",
	"white-space" : "white-space",
	"word-spacing" : "word-spacing",
	"word-break" : "word-break",
	"word-wrap" : "word-wrap",
	"z-index" : "z-index",
	}
